source 'https://rubygems.org'
gemspec

gem 'rb-readline'
gem 'pry'
group(:development, :test) do
  gem "simplecov"
  # for testing new chefstyle rules
  gem "chefstyle", git: "https://github.com/chef/chefstyle.git", branch: "master"
end